In [19]:
import numpy as np

t = np.array([0., 1., 2., 3., 4., 5., 6.])
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank of t:  1
Shape of t:  (7,)


In [20]:
print('t[0], t[1], t[-1]', t[0], t[1], t[-1])

t[0], t[1], t[-1] 0.0 1.0 6.0


In [21]:
print(t[2:5], t[4:-1])

[2. 3. 4.] [4. 5.]


In [22]:
t = np.array([
    [1., 2., 3.],
    [4., 5., 6.],
    [7., 8., 9.],
    [10., 11., 12.],
])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [23]:
t.shape

(4, 3)

In [24]:
t.ndim

2

In [25]:
import torch
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [26]:
print(t.dim())
print(t.shape)
print(t.size())

1
torch.Size([7])
torch.Size([7])


In [27]:
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [28]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                       ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [29]:
print(t.dim())
print(t.size())

2
torch.Size([4, 3])


In [30]:
print(t[:, 1])
print(t[:, 1].size())

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])


In [31]:
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


In [32]:
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3])
print(m1 + m2)

tensor([[4., 5.]])


In [33]:
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


In [34]:
m1 = torch.FloatTensor([[1, 2],
                         [3, 4]])
m2 = torch.FloatTensor([[1],
                         [2]])
print('Shape of Matrix 1: ', m1.shape)
print('Shape of Matrix 2: ', m2.shape)
print(m1.matmul(m2))

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [35]:
m1 = torch.FloatTensor([[1, 2],
                        [3, 4]])
m2 = torch.FloatTensor([[1],
                        [2]])
print('Shape of Matrix1: ', m1.shape)
print('Shape of Matrix2: ', m2.shape)
print(m1 * m2)
print(m1.mul(m2))

Shape of Matrix1:  torch.Size([2, 2])
Shape of Matrix2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


In [36]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [37]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [38]:
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


In [39]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)
print(t.max())

tensor([[1., 2.],
        [3., 4.]])
tensor(4.)


In [40]:
print(t.max(dim=0))

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


In [41]:
print('Max: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1])

Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [42]:
t = np.array([
              [
              [0, 1, 2],
              [3, 4, 5]],
              [[6, 7, 8],
              [9, 10, 11]
                          ]
              ])
tf = torch.FloatTensor(t)
print(tf.shape)

torch.Size([2, 2, 3])


In [44]:
print(tf.view([-1, 3]))
print(tf.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [ ]:
print(tf.view([-1,1, 3]))
print(tf.view([-1,1, 3]).shape)