In [1]:
# Pytorch
# numpy가 지원하는 연산들을 GPU에서 할 수 있도록 함
# 높은 유연성과 성능을 제공하는 딥러닝 지원
# 따라서, Numpy와 유사한 측면이 많음.

In [2]:
import torch

In [3]:
# Tensor는 numpy의 ndarray와 상당히 유사한 구조를 지님
# scalar(0D 텐서)
# scalar는 numpy로 만들 수 있음

In [4]:
import numpy as np
data1 = np.array(10)
print(data1, data1.ndim, data1.shape) # ndim은 aixs축, shape은 행렬의 차원을 의미함

10 0 ()


In [5]:
# Vector (1D 텐서)
# vector부터는 pytorch의 tensor로 만들 수 있음
# shape는 torch.size([3])와 같이 표현됨

In [8]:
data1 = torch.FloatTensor([1, 2]) #1, 2 원소를 가진 1D 텐서 선언
print(data1, data1.dim(), data1.shape)
data2 = torch.FloatTensor(3) # 임의의 3개의 원소를 가진 1D 텐서 선언
print(data2, data2.dim(), data2.shape) #dim()은 축, shape은 행렬의 차원을 의미함

tensor([1., 2.]) 1 torch.Size([2])
tensor([1.0078e+00, 4.7429e+30, 5.6052e-45]) 1 torch.Size([3])


In [9]:
# matrix(2D 텐서)
data3 = torch.FloatTensor(3, 2) # shape을 기반으로 임의의 원소값을 가진 텐서 선언
print(data3, data3.dim(), data3.shape)
data4 = torch.FloatTensor([ [1,2], [3, 4], [5, 6]])
print(data4, data4.dim(), data4.shape) # dim()은 axis(축) == 열과 동일

tensor([[5.3244e+22, 1.0015e-11],
        [1.6779e+22, 3.3611e+21],
        [1.0978e-05, 6.4531e-07]]) 2 torch.Size([3, 2])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]]) 2 torch.Size([3, 2])


In [11]:
# 3D 텐서
data5 = torch.FloatTensor(3, 2, 1) # 차원의 수, 행, 열 
print(data5, data5.dim(), data5.shape)

# 차원의 수는 행렬이 뭉탱이로 몇개가 있냐임
# 즉 위의 3, 2, 1은 2행 1열의 데이터가 3뭉치 존재한다는 의미임.

data6 = torch.FloatTensor([ [ [1], [2] ], [ [3], [4] ], [ [5], [6] ] ])
print(data6, data6.dim(), data6.shape)

tensor([[[2.6254e-06],
         [4.1727e+21]],

        [[2.5933e-09],
         [2.1271e-07]],

        [[4.2654e-08],
         [1.0811e-05]]]) 3 torch.Size([3, 2, 1])
tensor([[[1.],
         [2.]],

        [[3.],
         [4.]],

        [[5.],
         [6.]]]) 3 torch.Size([3, 2, 1])


In [12]:
# 밖에서부터 안쪽으로 텐서 선언 이해
data7 = torch.FloatTensor([ [1], [2], [3] ])
print(data7, data7.dim(), data7.shape)

data8 = torch.FloatTensor([ [1, 2, 3] ])
print(data8, data8.dim(), data8.shape)

tensor([[1.],
        [2.],
        [3.]]) 2 torch.Size([3, 1])
tensor([[1., 2., 3.]]) 2 torch.Size([1, 3])


In [13]:
# Tensor 생성 주요 메서드